version: "3"

services:

  app:
    image: earosb/iipzs-hojadiaria
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.6
    restart: unless-stopped
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - data:/var/lib/mysql
      - ./backups:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=icilicafalpzs.cl
      - LETSENCRYPT_HOST=icilicafalpzs.cl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/ssl

volumes:
  data:
    driver: "local"
