version: "3"

services:

  app:
    build:
      args:
        user: nunan
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.6
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - data:/var/lib/mysql
      - ./backups:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=icilicafalpzs.cl
      - LETSENCRYPT_HOST=icilicafalpzs.cl
    ports:
      - "80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/proxy/certs:/etc/nginx/certs
      - ./docker/proxy/vhost:/etc/nginx/vhost.d
      - ./docker/proxy/html:/usr/share/nginx/html

  companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-companion
    environment:
      - DEFAULT_EMAIL=eduardoaros@pm.me
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/proxy/certs:/etc/nginx/certs
      - ./docker/proxy/vhost:/etc/nginx/vhost.d
      - ./docker/proxy/html:/usr/share/nginx/html

volumes:
  data:
    driver: "local"
